name: continuous

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            10.0.x
      - name: 'Cache: ~/.nuget/packages'
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-
      - name: Restore
        run: dotnet restore src/MudBlazor.Templates.sln
      - name: Build
        run: dotnet build src/MudBlazor.Templates.sln --configuration Release --no-restore
      - name: Pack
        run: dotnet pack src/MudBlazor.Templates.sln --configuration Release --no-build --output artifacts/packages
      - name: 'Publish: packages'
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: artifacts/packages
